import { Template } from 'meteor/templating'
import 'ion-rangeslider'
import '../js/lolliclock.js'
import './layout.js'
import './pages/settings.js'
import './pages/add-food.js'
import './pages/add-symptoms.js'
import './pages/results.js'
import './pages/list.js'
import './pages/item-food.js'
import './pages/item-symptoms.js'
import './pages/update-food.js'
import './pages/update-symptoms.js'
